// Generates the factual summary block in README.md from data/seed (single source of truth).
// Run: npm run stats. CI regenerates and the count assertions in qa.ts guard against drift.
import fs from "fs";
import path from "path";
import type { Designation, OwnershipLink } from "../src/lib/types";

const SEED = path.join(__dirname, "..", "data", "seed");
const read = <T,>(n: string): T => JSON.parse(fs.readFileSync(path.join(SEED, n), "utf8"));

const vessels = read<unknown[]>("vessels.json");
const companies = read<unknown[]>("companies.json");
const designations = read<Designation[]>("designations.json");
const ownership = read<OwnershipLink[]>("ownership.json");
const companyLinks = read<unknown[]>("companylinks.json");
const voyages = read<unknown[]>("reportedvoyages.json");

const activeOfac = designations.filter((d) => d.currentStatus === "active" && d.authorityId === "ofac").length;
const activeUk = designations.filter((d) => d.currentStatus === "active" && d.authorityId !== "ofac").length;
const removed = designations.filter((d) => d.currentStatus === "removed").length;
const unver = designations.filter((d) => d.currentStatus === "current-unverified").length;

const roleCount: Record<string, number> = {};
for (const o of ownership) roleCount[o.role] = (roleCount[o.role] ?? 0) + 1;
const roleOrder = ["interestHolder", "beneficialOwner", "registeredOwner", "ownerOperator", "linkedTo", "shipManager", "ismManager", "operator"];
const preds = roleOrder.filter((r) => roleCount[r]).map((r) => `${r} ×${roleCount[r]}`).join(", ");

const programs = [...new Set(designations.map((d) => d.program).filter(Boolean))] as string[];

const block = [
  `- **${vessels.length} vessels** (IMO-keyed), **${companies.length} companies**, **${designations.length} designations**, **${ownership.length} vessel↔company relations**, **${companyLinks.length} company↔company links**, **${voyages.length} reported voyage**.`,
  `- **Designation status:** ${activeOfac} active (OFAC) + ${activeUk} active (UK) + ${removed} removed (OFAC) + ${unver} current-unverified designation records. The phrase "active sanctions" is avoided in favour of these explicit counts; note one hull (IMO 9277735) carries two separate listing events.`,
  `- **Programmes:** ${programs.join(", ")}.`,
  `- **Relation predicates** (matched to source wording): ${preds}.`,
].join("\n");

const README = path.join(__dirname, "..", "README.md");
let md = fs.readFileSync(README, "utf8");
const begin = "<!-- STATS:BEGIN (generated by scripts/stats.ts from data/seed — do not edit by hand) -->";
const end = "<!-- STATS:END -->";
const re = new RegExp(`${begin.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${end}`);
if (!re.test(md)) throw new Error("STATS markers not found in README.md");
md = md.replace(re, `${begin}\n${block}\n${end}`);
fs.writeFileSync(README, md, "utf8");
console.log("README STATS block regenerated:\n" + block);
